export const START  = 'START'
export const UPDATE = 'UPDATE'
export const RESET  = 'RESET'
export const BEGIN_BREAK = 'BEGIN_BREAK'
export const CHANGE_TIME_CONFIG = 'CHANGE_TIME'
export const SAVE_TIME_CONFIG = 'SAVE_TIME_CONFIG'
